# Generated by Django 6.0.3 on 2026-04-09 07:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_comment_published_remove_comment_views_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Motivatsiya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=300, unique=True)),
                ('cover', models.ImageField(upload_to='articles/covers/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_main', models.BooleanField(default=False)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='motivatsiya', to='main.category')),
            ],
        ),
    ]
