# Generated by Django 6.0.3 on 2026-04-09 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_motivatsiya'),
    ]

    operations = [
        migrations.RenameField(
            model_name='motivatsiya',
            old_name='is_main',
            new_name='Important',
        ),
    ]
