# Generated by Django 6.0.3 on 2026-04-09 08:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_is_main_motivatsiya_important'),
    ]

    operations = [
        migrations.RenameField(
            model_name='motivatsiya',
            old_name='Important',
            new_name='important',
        ),
        migrations.AddField(
            model_name='motivatsiya',
            name='author',
            field=models.CharField(default='Admin', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='motivatsiya',
            name='intro',
            field=models.TextField(default="Ma'lumot yo'q"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='motivatsiya',
            name='published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='motivatsiya',
            name='read_time',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='motivatsiya',
            name='tags',
            field=models.ManyToManyField(blank=True, to='main.tag'),
        ),
        migrations.AddField(
            model_name='motivatsiya',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='motivatsiya',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.category'),
        ),
        migrations.AlterField(
            model_name='motivatsiya',
            name='cover',
            field=models.ImageField(upload_to='motivatsiyas/covers/'),
        ),
    ]
