# Generated by Django 6.0.3 on 2026-04-09 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rename_important_motivatsiya_important_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='motivatsiya',
            options={'ordering': ['-created_at'], 'verbose_name': 'Motivatsiya', 'verbose_name_plural': 'Motivatsiyalar'},
        ),
        migrations.AddField(
            model_name='comment',
            name='motivatsiya',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='main.motivatsiya'),
        ),
        migrations.AddField(
            model_name='context',
            name='motivatsiya',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contexts', to='main.motivatsiya'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='article',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='main.article'),
        ),
        migrations.AlterField(
            model_name='context',
            name='article',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contexts', to='main.article'),
        ),
        migrations.AlterField(
            model_name='motivatsiya',
            name='author',
            field=models.CharField(max_length=255, verbose_name='Muallif'),
        ),
        migrations.AlterField(
            model_name='motivatsiya',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.category', verbose_name='Kategoriya'),
        ),
        migrations.AlterField(
            model_name='motivatsiya',
            name='cover',
            field=models.ImageField(upload_to='motivatsiyas/covers/', verbose_name='Muqova rasmi'),
        ),
        migrations.AlterField(
            model_name='motivatsiya',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt'),
        ),
        migrations.AlterField(
            model_name='motivatsiya',
            name='important',
            field=models.BooleanField(default=False, verbose_name='Muhim (Asosiy)'),
        ),
        migrations.AlterField(
            model_name='motivatsiya',
            name='intro',
            field=models.TextField(verbose_name='Qisqacha mazmun'),
        ),
        migrations.AlterField(
            model_name='motivatsiya',
            name='published',
            field=models.BooleanField(default=False, verbose_name='Nashr qilingan'),
        ),
        migrations.AlterField(
            model_name='motivatsiya',
            name='read_time',
            field=models.DurationField(blank=True, null=True, verbose_name="O'qish vaqti"),
        ),
        migrations.AlterField(
            model_name='motivatsiya',
            name='tags',
            field=models.ManyToManyField(blank=True, to='main.tag', verbose_name='Teglar'),
        ),
        migrations.AlterField(
            model_name='motivatsiya',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Sarlavha'),
        ),
        migrations.AlterField(
            model_name='motivatsiya',
            name='views',
            field=models.PositiveIntegerField(default=0, verbose_name="Ko'rishlar soni"),
        ),
    ]
