# Generated by Django 6.0.3 on 2026-04-14 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_motivatsiya_options_comment_motivatsiya_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='motivatsiya',
        ),
        migrations.RemoveField(
            model_name='context',
            name='motivatsiya',
        ),
        migrations.AddField(
            model_name='article',
            name='is_motivation',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='article',
            name='published',
            field=models.BooleanField(default=True),
        ),
        migrations.DeleteModel(
            name='Motivatsiya',
        ),
    ]
